--5월 식품들의 총매출 조회하기

SELECT FO.PRODUCT_ID, FR.PRODUCT_NAME,
       SUM(FO.AMOUNT * FR.PRICE) AS "TOTAL_SALES"
FROM FOOD_ORDER FO
INNER JOIN FOOD_PRODUCT FR
    ON FO.PRODUCT_ID = FR.PRODUCT_ID
WHERE TO_CHAR(FO.PRODUCE_DATE, 'YYYYMM') = '202205'
GROUP BY FO.PRODUCT_ID, FR.PRODUCT_NAME
ORDER BY SUM(FO.AMOUNT * FR.PRICE) DESC, FO.PRODUCT_ID